### ISSUE TITLE
A question about TransTEx

### ISSUE THREAD

**Issue by MilaDong** [pallavisurana1/TransTEx#1]
> fold_change_max_df = fold_change_max_TSp(matrix_fold_change)
Error in `.rowNamesDF<-`(x, value = value): 'row.names' contain missing values

When I check  
> any(is.na(rownames(matrix_fold_change)))
[1] FALSE

![1](https://github.com/user-attachments/assets/787e4b79-1e61-49e5-80f9-7bedf24eefb7)
Other files can be generated

**Comment by pallavisurana1** [comment]
Hi @MilaDong Can you please print matrix_fold_change[1:5, 1:5]
The function needs rownames to work as in the R documentation. Can you please send this.

Thanks

**Comment by MilaDong** [comment]
Hi I print matrix_fold_change[1:5, 1:5]


&gt; matrix_fold_change[1:5, 1:5]
   tissue      sample ENSTENSMMUG00000000055 1     eye Sample1-A-3               3.582581 2 shiguan Sample1-a-5              36.929583 3  naogan Sample1-B-3              22.491607 4 xiaonao Sample1-C-3              23.947184 5   weiti Sample1-c-5              33.842178   ENSTENSMMUG00000000066 ENSTENSMMUG00000000079 1                      0              0.6906340 2                      0              0.1167222 3                      0              0.0000000 4                      0              0.7551557 5                      0              0.3137920

This is a picture



Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pallavisurana1/TransTEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 上午7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pallavisurana1/TransTEx] A question about TransTEx (Issue #1)





 
Hi @MilaDong Can you please print matrix_fold_change[1:5, 1:5]
 The function needs rownames to work as in the R documentation. Can you please send this.
 
Thanks

**Comment by pallavisurana1** [comment]
Hi @MilaDong 
The function fold_change_TSp is written for human Transcripts. Try the function below.

```
fold_change_TSp_all_orgs <- function(data, category = "tissue-specific", tissue_interest, gene_prefix = "ENST") {
  # Filter and prepare data
  data <- data %>%
    select(starts_with(gene_prefix) | any_of(c("tissue", "sample")))

  # mean TPM in tissue of interest
  mean_tpm_df <- data %>%
    filter(tissue %in% tissue_interest) %>%
    group_by(tissue) %>%
    summarise(across(starts_with(gene_prefix), mean, na.rm = TRUE))

  # mean TPM not in tissue of interest
  not_mean_tpm_df <- bind_rows(lapply(unique(data$tissue), function(g) {
    df_not_in <- data %>%
      filter(tissue != g) %>%
      summarise(across(starts_with(gene_prefix), mean, na.rm = TRUE), .groups = 'drop') %>%
      mutate(tissue = g)
  }))

  # Calculate fold change
  fc <- log2(mean_tpm_df[, -which(names(mean_tpm_df) == "tissue")] / not_mean_tpm_df[, -which(names(not_mean_tpm_df) == "tissue")])
  return(data.frame(tissue = mean_tpm_df$tissue, fc))
}

# Usage
fold_change_TSp_all_orgs(data, tissue_interest = c("Brain", "Liver"), gene_prefix = "ENSTENSMMUG")
```
